# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: "postgres:11.1"
    container_name: "postgres-testcontainer-example"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql